name: CICD

on: 
  workflow_diapatch: 

jobs:
  code:
    runs-on: ubuntu-latest
    steps: 
      - name: clone the code
        run: echo "cloning the Code"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build using Docker
        run: echo "Building usind Docker"
        
  test:
    run: ubuntu-latest
    steps:
      - name: Running test cases
        run: echo "Testing the app"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on the machine 
        run: echo "Delploying the code"
