name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Code
        run: echo "Cloning the Code"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build using Docker
        run:  echo "Building using Docker"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Running Test Cases
        run: echo "testing the app"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying on the machine
        run: echo "Deployinf the Code"
